# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mathbattle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_978580db12dd44908b063956234d78c9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9d016d873cf14865bbb40a3cafdb3440 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_978580db12dd44908b063956234d78c9 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mathbattle'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_634b14f775a3420caa0b7bbbe95741e5 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_978580db12dd44908b063956234d78c9 }}/appsvc/staticsite:${{ github.sha }}'